added support for other exstension types
daboth/pagan pull request #10
Opened 2019-10-31 21:01 UTC by xXraxFraeyXx

2019-11-04 08:20 UTC, ofalk requested changes
It's not my call, but overall this code isn't clean and shouldn't be merged this way in my honest opinion.
However, I'd appreciate the support for different extensions.

@daboth I hope you don't mind I reviewed this.

2019-11-04 08:20 UTC, ofalk commented on pagan/pagan.py
> +    def save(self, path=DEFAULT_OUTPUT_PATH, filename=DEFAULT_FILENAME, exstension):
typo. => extension

2019-11-04 08:20 UTC, ofalk commented on pagan/pagan.py
> +        if !str.startswith(extensionT, ".")
where does this trailing uppercase T come frome? and it's not the same as the above exstension, which should have been extension.

2019-11-04 08:20 UTC, ofalk commented on pagan/pagan.py
> +        	extension = str.subtext(exstension, 1 - len(exstension));
if you wanted to make a difference between this 'extension' here and the above - i'd go for final_extension or something like that.

2019-11-04 08:20 UTC, ofalk commented on pagan/pagan.py
> +        if filename[-4:] == "." + exstension:
see above.

2019-11-04 08:20 UTC, ofalk commented on pagan/pagan.py
> +        filepath = ("%s%s." + exstension % (path, filename))
see above.

2019-11-04 08:20 UTC, ofalk commented on pagan/pagan.py
> +        filepath = os.path.join(path, "%s." + exstension % filename)
see above.

2019-11-04 08:20 UTC, ofalk commented on pagan/pagan.py
> +        self.img.save(filepath, str.upper(exstension)
see above.

2019-11-06 14:30 UTC, daboth commented
Thank you @ofalk for reviewing. I also think it would be nice to include more extensions, but i need to do some testing first (e.g. picture quality, ect. for non-png images). I would also prefer to use constants for supported extensions instead of a simple variable.

2019-11-07 08:19 UTC, ofalk commented
Sorry for the noise here. I've reworked the idea in pull request #11 but forgot to squash correctly. I'd suggest to close this pull in favour of mine :-)

2019-11-07 20:06 UTC, closed without merging

2019-11-07 20:07 UTC, daboth commented
Closed in favor of #11. I appreciate every commit though, the idea was good! Will test and merge #11 when i have some spare time :)